language: python
sudo: required
dist: xenial
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install codecov
  - pip install -r test-requirements.txt -r requirements.txt
script:
  - make test
after_success:
  - coverage report
  - codecov
