[tool.black]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.isort]
profile = "black"
skip = ".tox"

[tool.coverage.run]
source = ["pingeon"]

[tool.coverage.report]
omit = ["tests"]
show_missing = true

[tool.pytest.ini_options]
testpaths = ["tests"]
flake8-max-line-length = 88
